import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          'GetOn': "Get On",
          'CreateyourprofiletostartyourJorneywithus':
              "Create your profile to start your Jorney with us",
          'FullName': "Full Name",
          'BloodType': "Blood Type",
          'A': "A",
          'Email': "Email",
          'PhoneNumber': "Phone Number",
          'Email:': "Email:",
          'PhoneNumber:': "Phone Number:",
          'Password': "Password",
          'SIGNUP': "SIGN UP",
          'AlreadyhaveanAccount?': "Already have an Account?",
          "dontHaveAccount?": "Don't have an Account? ",
          'Signin': "Sign in",
          'WelcomeBack,': "WelcomeBack,",
          'Makeitwork,': "Make It work,",
          'Makeitright,': "Make it right,",
          'Makeitfast.': "Make it fast.",
          'ForgetePassword': "Forgete Password",
          'OR': "or",
          'SignInWithGoogle': "Sign In With Google",
          'DonthaveanAccount?': "Dont have an Account?",
          'SignUp': "Sign Up",
          'BloodDonation': "Blood Donation",
          'UserLoggedInSuccessfuly': "User Logged-In Successfuly",
          'Ok': "Ok",
          'Location': "Location",
          'MyRequest': "My Request",
          'Donateblood and save lives': "Donate blood and save lives",
          'BloodRequest': "Blood Request",
          'Donation': "Donation",
          'Typeamessage': "Type a message",
          'Type': "Type",
          'M': "M",
          'DeadBlood': "Dead Blood",
          'DonateNow': "Donate Now",
          'Reason': "Reason",
          'UnitRequired': "UnitRequired",
          'DeadLine': "DeadLine",
          'Hospital': "Hospital",
          'PersonInCharge': "Person In Charge",
          'ContactNumber': "Contact Number",
          'PatientName': "Patient Name",
          'CreateBloodRequest': "Create Blood Request",
          'Update': "Update",
          'Requests': "Requests",
          'BirthDate': "Birth Date",
          'null': "null",
          'MedicalCondition': "Medical Condition",
          'Whocanidonate': "Who can i donate",
          'Logout': "Logout",
          'Home': "Home",
          'RequestBlood': "Request Blood",
          'DonateBlood': "Donate blood",
          'MyDonations': "My Donations",
          'Nearby': "Nearby",
          'Messages': "Messages",
          'Sponser': "Sponser",
          'SponserName:': "Sponser Name:",
          'AccessToken': "Access Token",
          'InvalidEmailorPassword': "Invalid Email or Password",
          'Registrationcompletedsuccessfully':
              "Registration completed successfully",
          'Thisemailisalreadyregistered': "This email is already registered",
          'Requestbloodfromdonors': "Request blood from donors",
          'Bloodrequestcreatedsuccessfully':
              "Blood request created successfully",
          'Errorcreatingbloodrequest': "Error creating blood request",
          'Hospital:      ': "Hospital:      ",
          'Deadline:     ': "Deadline:     ",
          'Contact:      ': "Contact:      ",
          'RequiredUnit:      ': "RequiredUnit:      ",
          'View': "View",
          'Completed:': "Completed:",
          'Completed': "Completed",
          'SuccessfulyDonated': "Successfuly Donated",
          'AlreadyDonated': "Already Donated",
          'userisapprovedsuccessfully': "user is approved successfully",
          'userapprovalfailed': "user approval failed",
          'Approve': "Approve",
          'Setting': "Setting",
          'ChangeLanguage': "Change Language",
          'SaveChanges': "Save Changes"
        },
        "et_ET": {
          'GetOn': "ተሳፈር",
          'CreateyourprofiletostartyourJorneywithus':
              "ጉዞዎን ከእኛ ጋር ለመጀመር መገለጫዎን ይፍጠሩ",
          'FullName': "ሙሉ ስም",
          'BloodType': "የደም አይነት",
          'A': "A",
          'Email': "ኢ-ሜይል",
          'PhoneNumber': "ስልክ ቁጥር",
          'Email:': "ኢ-ሜይል",
          'PhoneNumber:': "ስልክ ቁጥር",
          'Password': "የይለፍ ቃል",
          'SIGNUP': "ተመዝገብ",
          'AlreadyhaveanAccount?': "መለያ አለህ?",
          "dontHaveAccount?": "መለያ የሎትም?",
          'Signin': "ግባ",
          'WelcomeBack,': "እንኳን ደህና መጣህ,",
          'Makeitwork,': "እንዲሰራ ያድርጉት፣",
          'Makeitright,': "በትክክል ያድርጉት፣",
          'Makeitfast.': "በፍጥነት ያድርጉት።",
          'ForgetePassword': "የይለፍ ቃል እርረሳ",
          'OR': "ወይም",
          'SignInWithGoogle': "በGoogle ይግቡ",
          'DonthaveanAccount?': "መለያ የለህም?",
          'SignUp': "ተመዝገብ",
          'BloodDonation': "የደም ልገሳ",
          'UserLoggedInSuccessfuly': "ተጠቃሚ በተሳካ ሁኔታ ገብቷል።",
          'Ok': "እሺ",
          'Location': "አካባቢ/መገኛ",
          'MyRequest': "የእኔ ጥያቄ",
          'Donatebloodandsavelives': "ደም ለግሱ እና ህይወትን ያድኑ",
          'BloodRequest': "የደም ጥያቄ",
          'Donation': "ልገሳ",
          'Typeamessage': "መልእክት ያስቀምጡ",
          'Type': "አይነት",
          'M': "ወ",
          'DonateBlood': "ደም ይለግሱ",
          'DonateNow': "አሁን ይለግሱ",
          'Reason': "ምክንያት",
          'UnitRequired': "የደም መጠን",
          'DeadLine': "ማለቂያ ሰአት",
          'Hospital': "ሆስፒታል",
          "Hospital:      ": "ሆስፒታል:      ",
          'Deadline:     ': "ማለቂያ ሰአት:     ",
          'Contact:      ': "የስልክ ቁጥር:      ",
          'RequiredUnit:      ': "የደም መጠን:      ",
          'PersonInCharge': "ኃላፊነት የሚወስድ ሰው",
          'ContactNumber': "የስልክ ቁጥር",
          'PatientName': "የታካሚ ስም",
          'CreateBloodRequest': "የደም ጥያቄን ይፍጠሩ",
          'Update': "አዘምን",
          'Requests': "ጥያቄዎች",
          'BirthDate': "የተወለዱበት ቀን",
          'null': "ባዶ",
          'MedicalCondition': "የሕክምና ሁኔታ",
          'Whocanidonate': "ለማን መለገስ እችላለሁ",
          'Logout': "ውጣ",
          'Home': "ዋና ገጽ",
          'RequestBlood': "ደም ይጠይቁ",
          'MyDonations': "የእኔ ልገሳዎች",
          'Nearby': "በአቅራቢያ",
          'Messages': "መልዕክቶች",
          'Sponser': "አጋርወችህ",
          'SponserName:': "የአጋርወችህ ስም",
          'AccessToken': "መለያየን ተጠቀም",
          "Registrationcompletedsuccessfully": "በትክክል ተመዝግበዋል",
          'Requestbloodfromdonors': "ደም ፈልግ",
          'Bloodrequestcreatedsuccessfully': "የደም ጥያቄወ በተሳካ ሁኔታ ተፈጥሯል",
          'Errorcreatingbloodrequest': "የደም ጥያቄወ አልተሳካም",
          'View': "ተመልከት",
          'Completed:': "አልቋል:",
          'Completed': "አልቋል:",
          'SuccessfulyDonated': "በተሳካ ሁኔታ ደም ለግሰዋ",
          'AlreadyDonated': "ከዚህ በፊት ለግሰዋል",
          'userisapprovedsuccessfully': "መለገስወ ተረጋግጧል",
          'userapprovalfailed': "ልገሳወ አልተረጋገጠም",
          'Approve': "አረጋግጥ",
          'Setting': "ማቀናበሪያ",
          'ChangeLanguage': "ቋንቋ ቀይር",
          'SaveChanges': "የተቀየሩትን አስቀምጥ"
        }
      };
}
